/**
 * Default Offline Curriculum Quizzes and Graded Questions
 * Provides immediate offline capability even before first network sync.
 */

export const DEFAULT_OFFLINE_QUIZZES = [
  // Class 10
  {
    id: 'quiz:c10:math:real_numbers',
    subjectId: 'subject:math',
    subjectName: 'Mathematics',
    moduleId: 'module:c10:real_numbers',
    moduleTitle: 'Real Numbers & Polynomials',
    className: 'Class 10',
    title: 'Class 10 Real Numbers & Polynomials Mastery Quiz',
    description: 'Assess prime factorisations, HCF/LCM relationship, and zeroes of quadratic polynomials.',
    difficulty: 'medium',
    timeLimit: 600,
    passingScore: 70,
    isPublished: true,
    isUnlocked: true,
    unlocked: true,
    state: 'UNLOCKED',
    progress: 100,
    totalLessons: 0,
    completedLessons: 0,
  },
  {
    id: 'quiz:c10:sci:light_optics',
    subjectId: 'subject:science',
    subjectName: 'Science',
    moduleId: 'module:c10:light_optics',
    moduleTitle: 'Light: Reflection & Refraction',
    className: 'Class 10',
    title: 'Class 10 Light: Reflection & Refraction Quiz',
    description: 'Test your grasp of spherical mirrors, mirror formula, Snell’s law, and lens power.',
    difficulty: 'medium',
    timeLimit: 600,
    passingScore: 70,
    isPublished: true,
    isUnlocked: true,
    unlocked: true,
    state: 'UNLOCKED',
    progress: 100,
    totalLessons: 0,
    completedLessons: 0,
  },
  {
    id: 'quiz:c10:sci:chemical_reactions',
    subjectId: 'subject:science',
    subjectName: 'Science',
    moduleId: 'module:c10:chem_reactions',
    moduleTitle: 'Chemical Reactions & Equations',
    className: 'Class 10',
    title: 'Class 10 Chemical Reactions & Equations Test',
    description: 'Questions on balanced equations, redox processes, exothermic reactions, and catalysts.',
    difficulty: 'medium',
    timeLimit: 600,
    passingScore: 70,
    isPublished: true,
    isUnlocked: true,
    unlocked: true,
    state: 'UNLOCKED',
    progress: 100,
    totalLessons: 0,
    completedLessons: 0,
  },
  {
    id: 'quiz:c10:eng:grammar_mastery',
    subjectId: 'subject:english',
    subjectName: 'English',
    moduleId: 'module:c10:eng_grammar',
    moduleTitle: 'English Grammar & Literature Mastery',
    className: 'Class 10',
    title: 'Class 10 English: Grammar & Reported Speech Quiz',
    description: 'Test your command of indirect speech, passive voice, and grammatical accuracy.',
    difficulty: 'easy',
    timeLimit: 600,
    passingScore: 70,
    isPublished: true,
    isUnlocked: true,
    unlocked: true,
    state: 'UNLOCKED',
    progress: 100,
    totalLessons: 0,
    completedLessons: 0,
  },

  // Class 9
  {
    id: 'quiz:c9:sci:motion_force',
    subjectId: 'subject:science',
    subjectName: 'Science',
    moduleId: 'module:c9:motion_force',
    moduleTitle: 'Motion & Laws of Force',
    className: 'Class 9',
    title: 'Class 9 Physics: Motion & Newton’s Laws Quiz',
    description: 'Kinematics and dynamics assessment covering velocity, acceleration, and F = ma.',
    difficulty: 'medium',
    timeLimit: 600,
    passingScore: 70,
    isPublished: true,
    isUnlocked: true,
    unlocked: true,
    state: 'UNLOCKED',
    progress: 100,
    totalLessons: 0,
    completedLessons: 0,
  },
  {
    id: 'quiz:c9:math:number_systems',
    subjectId: 'subject:math',
    subjectName: 'Mathematics',
    moduleId: 'module:c9:number_systems',
    moduleTitle: 'Number Systems & Coordinate Geometry',
    className: 'Class 9',
    title: 'Class 9 Mathematics: Number Systems & Geometry Test',
    description: 'Examine rational vs irrational numbers, decimal expansions, and Cartesian plane.',
    difficulty: 'medium',
    timeLimit: 600,
    passingScore: 70,
    isPublished: true,
    isUnlocked: true,
    unlocked: true,
    state: 'UNLOCKED',
    progress: 100,
    totalLessons: 0,
    completedLessons: 0,
  },

  // Class 8
  {
    id: 'quiz:c8:math:rational_numbers',
    subjectId: 'subject:math',
    subjectName: 'Mathematics',
    moduleId: 'module:c8:rational_numbers',
    moduleTitle: 'Rational Numbers & Linear Equations',
    className: 'Class 8',
    title: 'Class 8 Mathematics: Rational Numbers & Equations',
    description: 'Master operations on rational numbers and linear equations in one variable.',
    difficulty: 'easy',
    timeLimit: 600,
    passingScore: 70,
    isPublished: true,
    isUnlocked: true,
    unlocked: true,
    state: 'UNLOCKED',
    progress: 100,
    totalLessons: 0,
    completedLessons: 0,
  },
  {
    id: 'quiz:c8:sci:force_pressure',
    subjectId: 'subject:science',
    subjectName: 'Science',
    moduleId: 'module:c8:force_pressure',
    moduleTitle: 'Force, Pressure & Friction',
    className: 'Class 8',
    title: 'Class 8 Science: Force, Pressure & Friction',
    description: 'Fundamental quiz on contact forces, gravitational force, and atmospheric pressure.',
    difficulty: 'easy',
    timeLimit: 600,
    passingScore: 70,
    isPublished: true,
    isUnlocked: true,
    unlocked: true,
    state: 'UNLOCKED',
    progress: 100,
    totalLessons: 0,
    completedLessons: 0,
  },
];

export const DEFAULT_OFFLINE_QUESTIONS = {
  'quiz:c10:math:real_numbers': [
    {
      id: 'q:c10:m:rn:1',
      quiz_id: 'quiz:c10:math:real_numbers',
      text: 'What is the HCF of 96 and 404 using the Fundamental Theorem of Arithmetic?',
      options: ['4', '8', '2', '12'],
      correct_answer: '4',
      explanation: '96 = 2^5 * 3, 404 = 2^2 * 101. Lowest common prime factor power is 2^2 = 4.',
      order: 1,
    },
    {
      id: 'q:c10:m:rn:2',
      quiz_id: 'quiz:c10:math:real_numbers',
      text: 'If the zeroes of ax² + bx + c (a ≠ 0) are α and β, what is the value of α + β?',
      options: ['-b / a', 'c / a', 'b / a', '-c / a'],
      correct_answer: '-b / a',
      explanation: 'Sum of zeroes of quadratic polynomial = -b / a.',
      order: 2,
    },
    {
      id: 'q:c10:m:rn:3',
      quiz_id: 'quiz:c10:math:real_numbers',
      text: 'The decimal expansion of 13 / 3125 terminates after how many decimal places?',
      options: ['5', '4', '3', '6'],
      correct_answer: '5',
      explanation: '3125 = 5^5. Highest exponent is 5, so it terminates after 5 places.',
      order: 3,
    },
    {
      id: 'q:c10:m:rn:4',
      quiz_id: 'quiz:c10:math:real_numbers',
      text: 'If α and β are the zeroes of x² - 5x + 6, find the value of α * β.',
      options: ['6', '-6', '5', '-5'],
      correct_answer: '6',
      explanation: 'Product of zeroes α * β = c / a = 6 / 1 = 6.',
      order: 4,
    },
    {
      id: 'q:c10:m:rn:5',
      quiz_id: 'quiz:c10:math:real_numbers',
      text: 'Which of the following is an irrational number?',
      options: ['2 + √3', '2 - √4', '√9', '3.141414... (repeating)'],
      correct_answer: '2 + √3',
      explanation: 'Sum of rational and irrational number is always irrational.',
      order: 5,
    },
  ],
  'quiz:c10:sci:light_optics': [
    {
      id: 'q:c10:s:opt:1',
      quiz_id: 'quiz:c10:sci:light_optics',
      text: 'What is the focal length of a spherical mirror with a radius of curvature of 32 cm?',
      options: ['16 cm', '32 cm', '64 cm', '8 cm'],
      correct_answer: '16 cm',
      explanation: 'Focal length f = R / 2 = 32 / 2 = 16 cm.',
      order: 1,
    },
    {
      id: 'q:c10:s:opt:2',
      quiz_id: 'quiz:c10:sci:light_optics',
      text: 'Which mirror is used by dentists to see enlarged images of teeth?',
      options: ['Concave mirror', 'Convex mirror', 'Plane mirror', 'Cylindrical mirror'],
      correct_answer: 'Concave mirror',
      explanation: 'Concave mirror creates magnified virtual erect images when object is near.',
      order: 2,
    },
    {
      id: 'q:c10:s:opt:3',
      quiz_id: 'quiz:c10:sci:light_optics',
      text: 'What is the SI unit of power of a lens?',
      options: ['Dioptre (D)', 'Metre (m)', 'Watt (W)', 'Lumen (lm)'],
      correct_answer: 'Dioptre (D)',
      explanation: 'P = 1 / f(m). Unit is Dioptre (D).',
      order: 3,
    },
    {
      id: 'q:c10:s:opt:4',
      quiz_id: 'quiz:c10:sci:light_optics',
      text: 'According to Snell’s Law of Refraction, what ratio remains constant for a given pair of media?',
      options: ['sin(i) / sin(r)', 'sin(i) * sin(r)', 'cos(i) / cos(r)', 'tan(i) / tan(r)'],
      correct_answer: 'sin(i) / sin(r)',
      explanation: 'Snell’s Law: sin(i) / sin(r) = constant refractive index.',
      order: 4,
    },
    {
      id: 'q:c10:s:opt:5',
      quiz_id: 'quiz:c10:sci:light_optics',
      text: 'An object is placed at 2F₁ of a convex lens. Where is the image formed?',
      options: ['At 2F₂', 'At F₂', 'Between F₂ and 2F₂', 'At infinity'],
      correct_answer: 'At 2F₂',
      explanation: 'Real, inverted, same-sized image forms at 2F₂ on the opposite side.',
      order: 5,
    },
  ],
  'quiz:c10:sci:chemical_reactions': [
    {
      id: 'q:c10:s:cr:1',
      quiz_id: 'quiz:c10:sci:chemical_reactions',
      text: 'In the reaction: Fe + CuSO₄ → FeSO₄ + Cu, what type of reaction takes place?',
      options: ['Displacement reaction', 'Combination reaction', 'Decomposition reaction', 'Double displacement reaction'],
      correct_answer: 'Displacement reaction',
      explanation: 'Iron displaces copper from copper sulphate solution.',
      order: 1,
    },
    {
      id: 'q:c10:s:cr:2',
      quiz_id: 'quiz:c10:sci:chemical_reactions',
      text: 'Respiration is considered which type of reaction?',
      options: ['Exothermic reaction', 'Endothermic reaction', 'Photochemical reaction', 'Neutralization reaction'],
      correct_answer: 'Exothermic reaction',
      explanation: 'Oxidation of glucose releases energy, making it exothermic.',
      order: 2,
    },
    {
      id: 'q:c10:s:cr:3',
      quiz_id: 'quiz:c10:sci:chemical_reactions',
      text: 'What gas is evolved when dilute hydrochloric acid reacts with zinc granules?',
      options: ['Hydrogen gas (H₂)', 'Oxygen gas (O₂)', 'Carbon dioxide (CO₂)', 'Chlorine gas (Cl₂)'],
      correct_answer: 'Hydrogen gas (H₂)',
      explanation: 'Zn + 2HCl → ZnCl₂ + H₂↑.',
      order: 3,
    },
    {
      id: 'q:c10:s:cr:4',
      quiz_id: 'quiz:c10:sci:chemical_reactions',
      text: 'In the redox reaction: CuO + H₂ → Cu + H₂O, which substance is reduced?',
      options: ['CuO', 'H₂', 'Cu', 'H₂O'],
      correct_answer: 'CuO',
      explanation: 'CuO loses oxygen to form Cu, so CuO is reduced.',
      order: 4,
    },
    {
      id: 'q:c10:s:cr:5',
      quiz_id: 'quiz:c10:sci:chemical_reactions',
      text: 'Why are chips packets flushed with nitrogen gas?',
      options: ['To prevent rancidity (oxidation of fats)', 'To add flavor', 'To make packets heavier', 'To absorb moisture only'],
      correct_answer: 'To prevent rancidity (oxidation of fats)',
      explanation: 'Nitrogen gas prevents oils from being oxidized.',
      order: 5,
    },
  ],
  'quiz:c10:eng:grammar_mastery': [
    {
      id: 'q:c10:e:1',
      quiz_id: 'quiz:c10:eng:grammar_mastery',
      text: 'Identify the correct indirect speech: He said, "I am reading a book."',
      options: [
        'He said that he was reading a book.',
        'He said that he is reading a book.',
        'He told that he had been reading a book.',
        'He says that he was reading a book.'
      ],
      correct_answer: 'He said that he was reading a book.',
      explanation: 'Present continuous changes to past continuous in reported speech.',
      order: 1,
    },
    {
      id: 'q:c10:e:2',
      quiz_id: 'quiz:c10:eng:grammar_mastery',
      text: 'Change to passive voice: "The chef cooked a delicious meal."',
      options: [
        'A delicious meal was cooked by the chef.',
        'A delicious meal had cooked by the chef.',
        'A delicious meal is cooked by the chef.',
        'A delicious meal was being cooked by the chef.'
      ],
      correct_answer: 'A delicious meal was cooked by the chef.',
      explanation: 'Simple past active changes to was + past participle.',
      order: 2,
    },
  ],
  'quiz:c9:sci:motion_force': [
    {
      id: 'q:c9:s:mot:1',
      quiz_id: 'quiz:c9:sci:motion_force',
      text: 'What is the SI unit of acceleration?',
      options: ['m/s²', 'm/s', 'km/h', 'N·m'],
      correct_answer: 'm/s²',
      explanation: 'Acceleration is change in velocity over time: m/s².',
      order: 1,
    },
    {
      id: 'q:c9:s:mot:2',
      quiz_id: 'quiz:c9:sci:motion_force',
      text: 'Newton’s First Law of Motion is also known as the Law of:',
      options: ['Inertia', 'Momentum', 'Action-Reaction', 'Gravitation'],
      correct_answer: 'Inertia',
      explanation: 'First law defines inertia of rest and motion.',
      order: 2,
    },
  ],
  'quiz:c8:math:rational_numbers': [
    {
      id: 'q:c8:m:rn:1',
      quiz_id: 'quiz:c8:math:rational_numbers',
      text: 'What is the additive inverse of -7 / 19?',
      options: ['7 / 19', '-19 / 7', '19 / 7', '0'],
      correct_answer: '7 / 19',
      explanation: 'Additive inverse satisfies a + (-a) = 0.',
      order: 1,
    },
    {
      id: 'q:c8:m:rn:2',
      quiz_id: 'quiz:c8:math:rational_numbers',
      text: 'Solve the equation for x: 2x - 3 = 7.',
      options: ['x = 5', 'x = 4', 'x = 2', 'x = 10'],
      correct_answer: 'x = 5',
      explanation: '2x = 10 -> x = 5.',
      order: 2,
    },
  ],
  'quiz:c8:sci:force_pressure': [
    {
      id: 'q:c8:s:fp:1',
      quiz_id: 'quiz:c8:sci:force_pressure',
      text: 'Pressure is defined as:',
      options: ['Force per unit area (Force / Area)', 'Force * Area', 'Mass * Acceleration', 'Work / Time'],
      correct_answer: 'Force per unit area (Force / Area)',
      explanation: 'Pressure = Force perpendicular to surface / Area.',
      order: 1,
    },
    {
      id: 'q:c8:s:fp:2',
      quiz_id: 'quiz:c8:sci:force_pressure',
      text: 'Which of the following is a non-contact force?',
      options: ['Gravitational force', 'Frictional force', 'Muscular force', 'Tension force'],
      correct_answer: 'Gravitational force',
      explanation: 'Gravitational force acts across distances without physical contact.',
      order: 2,
    },
  ],
};
