/**
 * Default Curated Course Data for School Students (System 2)
 * Used as seed source and reliable fallback when Supabase table migration is pending.
 */

export const DEFAULT_COURSE_SUBJECTS = [
  // Class 4
  { id: 'csubj_c4_math', class: 'Class 4', subject_name: 'Mathematics', display_order: 1, icon: 'Calculator', is_active: true },
  { id: 'csubj_c4_sci', class: 'Class 4', subject_name: 'Science', display_order: 2, icon: 'FlaskConical', is_active: true },
  { id: 'csubj_c4_eng', class: 'Class 4', subject_name: 'English', display_order: 3, icon: 'BookOpen', is_active: true },

  // Class 5
  { id: 'csubj_c5_math', class: 'Class 5', subject_name: 'Mathematics', display_order: 1, icon: 'Calculator', is_active: true },
  { id: 'csubj_c5_sci', class: 'Class 5', subject_name: 'Science', display_order: 2, icon: 'FlaskConical', is_active: true },
  { id: 'csubj_c5_eng', class: 'Class 5', subject_name: 'English', display_order: 3, icon: 'BookOpen', is_active: true },

  // Class 6
  { id: 'csubj_c6_math', class: 'Class 6', subject_name: 'Mathematics', display_order: 1, icon: 'Calculator', is_active: true },
  { id: 'csubj_c6_sci', class: 'Class 6', subject_name: 'Science', display_order: 2, icon: 'FlaskConical', is_active: true },
  { id: 'csubj_c6_eng', class: 'Class 6', subject_name: 'English', display_order: 3, icon: 'BookOpen', is_active: true },

  // Class 7
  { id: 'csubj_c7_math', class: 'Class 7', subject_name: 'Mathematics', display_order: 1, icon: 'Calculator', is_active: true },
  { id: 'csubj_c7_sci', class: 'Class 7', subject_name: 'Science', display_order: 2, icon: 'FlaskConical', is_active: true },
  { id: 'csubj_c7_eng', class: 'Class 7', subject_name: 'English', display_order: 3, icon: 'BookOpen', is_active: true },

  // Class 8
  { id: 'csubj_c8_math', class: 'Class 8', subject_name: 'Mathematics', display_order: 1, icon: 'Calculator', is_active: true },
  { id: 'csubj_c8_sci', class: 'Class 8', subject_name: 'Science', display_order: 2, icon: 'FlaskConical', is_active: true },
  { id: 'csubj_c8_eng', class: 'Class 8', subject_name: 'English', display_order: 3, icon: 'BookOpen', is_active: true },
  { id: 'csubj_c8_sst', class: 'Class 8', subject_name: 'Social Science', display_order: 4, icon: 'BookOpen', is_active: true },

  // Class 9
  { id: 'csubj_c9_math', class: 'Class 9', subject_name: 'Mathematics', display_order: 1, icon: 'Calculator', is_active: true },
  { id: 'csubj_c9_sci', class: 'Class 9', subject_name: 'Science', display_order: 2, icon: 'FlaskConical', is_active: true },
  { id: 'csubj_c9_eng', class: 'Class 9', subject_name: 'English', display_order: 3, icon: 'BookOpen', is_active: true },
  { id: 'csubj_c9_sst', class: 'Class 9', subject_name: 'Social Science', display_order: 4, icon: 'BookOpen', is_active: true },

  // Class 10
  { id: 'csubj_c10_math', class: 'Class 10', subject_name: 'Mathematics', display_order: 1, icon: 'Calculator', is_active: true },
  { id: 'csubj_c10_sci', class: 'Class 10', subject_name: 'Science', display_order: 2, icon: 'FlaskConical', is_active: true },
  { id: 'csubj_c10_eng', class: 'Class 10', subject_name: 'English', display_order: 3, icon: 'BookOpen', is_active: true },
  { id: 'csubj_c10_cs', class: 'Class 10', subject_name: 'Computer Applications', display_order: 4, icon: 'Laptop', is_active: true },
];

export const DEFAULT_COURSE_VIDEOS = [
  // Class 4 Mathematics
  {
    id: 'cvid_c4_m1',
    subject_id: 'csubj_c4_math',
    title: '1. Introduction to Fractions',
    description: 'Learn what fractions mean, numerators, and denominators using visual shapes.',
    youtube_url: 'https://www.youtube.com/watch?v=ITce7f6K9as',
    duration: 480,
    display_order: 1,
    is_active: true,
  },
  {
    id: 'cvid_c4_m2',
    subject_id: 'csubj_c4_math',
    title: '2. Multiplication & Division Concepts',
    description: 'Master multi-digit multiplication and step-by-step division techniques.',
    youtube_url: 'https://www.youtube.com/watch?v=mvOkMYCygps',
    duration: 600,
    display_order: 2,
    is_active: true,
  },
  {
    id: 'cvid_c4_m3',
    subject_id: 'csubj_c4_math',
    title: '3. 2D Shapes, Symmetry & Geometry',
    description: 'Explore symmetrical patterns, polygons, and geometric spatial properties.',
    youtube_url: 'https://www.youtube.com/watch?v=24Uv8Cl5hvI',
    duration: 420,
    display_order: 3,
    is_active: true,
  },

  // Class 4 Science
  {
    id: 'cvid_c4_s1',
    subject_id: 'csubj_c4_sci',
    title: '1. How Plants Make Food: Photosynthesis',
    description: 'Discover chlorophyll, sunlight absorption, and oxygen production in leaves.',
    youtube_url: 'https://www.youtube.com/watch?v=D1Ymc311XS8',
    duration: 540,
    display_order: 1,
    is_active: true,
  },
  {
    id: 'cvid_c4_s2',
    subject_id: 'csubj_c4_sci',
    title: '2. The Human Digestive System',
    description: 'Follow food on its journey from mouth to stomach and nutrient absorption.',
    youtube_url: 'https://www.youtube.com/watch?v=VwrsL-lCzYo',
    duration: 660,
    display_order: 2,
    is_active: true,
  },
  {
    id: 'cvid_c4_s3',
    subject_id: 'csubj_c4_sci',
    title: '3. States of Matter: Solids, Liquids & Gases',
    description: 'Understand molecular arrangements and phase changes with fun examples.',
    youtube_url: 'https://www.youtube.com/watch?v=wclY8LIC-HE',
    duration: 480,
    display_order: 3,
    is_active: true,
  },
  {
    id: 'cvid_c4_s4',
    subject_id: 'csubj_c4_sci',
    title: '4. The Water Cycle in Nature',
    description: 'Learn how evaporation, condensation, and precipitation circulate Earth’s water.',
    youtube_url: 'https://www.youtube.com/watch?v=ncORPosDrjI',
    duration: 360,
    display_order: 4,
    is_active: true,
  },
  {
    id: 'cvid_c4_s5',
    subject_id: 'csubj_c4_sci',
    title: '5. Adaptations in Animals & Habitats',
    description: 'See how desert, polar, and aquatic animals survive in extreme environments.',
    youtube_url: 'https://www.youtube.com/watch?v=Z3W6n64F1xM',
    duration: 510,
    display_order: 5,
    is_active: true,
  },

  // Class 4 English
  {
    id: 'cvid_c4_e1',
    subject_id: 'csubj_c4_eng',
    title: '1. Nouns: Common, Proper & Collective',
    description: 'Learn to identify different types of nouns with sentence examples.',
    youtube_url: 'https://www.youtube.com/watch?v=84HYE8v_Kow',
    duration: 420,
    display_order: 1,
    is_active: true,
  },
  {
    id: 'cvid_c4_e2',
    subject_id: 'csubj_c4_eng',
    title: '2. Action Verbs & Helping Verbs',
    description: 'Learn how verbs express actions and support sentence clarity.',
    youtube_url: 'https://www.youtube.com/watch?v=Uq_Vw32m_7k',
    duration: 480,
    display_order: 2,
    is_active: true,
  },
  {
    id: 'cvid_c4_e3',
    subject_id: 'csubj_c4_eng',
    title: '3. Subject and Predicate in Sentences',
    description: 'Break down complete sentences into subjects and predicates accurately.',
    youtube_url: 'https://www.youtube.com/watch?v=fdUXxdmhIsw',
    duration: 360,
    display_order: 3,
    is_active: true,
  },
  {
    id: 'cvid_c4_e4',
    subject_id: 'csubj_c4_eng',
    title: '4. Reading Comprehension Skills',
    description: 'Strategies for reading passages, identifying main ideas, and answering questions.',
    youtube_url: 'https://www.youtube.com/watch?v=2y2Bf1t6Iks',
    duration: 540,
    display_order: 4,
    is_active: true,
  },

  // Class 5 Mathematics
  {
    id: 'cvid_c5_m1',
    subject_id: 'csubj_c5_math',
    title: '1. Introduction to Decimals & Place Value',
    description: 'Grasp tenths, hundredths, and converting fractions to decimals.',
    youtube_url: 'https://www.youtube.com/watch?v=t9vbmxPzBGE',
    duration: 540,
    display_order: 1,
    is_active: true,
  },
  {
    id: 'cvid_c5_m2',
    subject_id: 'csubj_c5_math',
    title: '2. Factors, Multiples & Prime Numbers',
    description: 'Find HCF and LCM easily using factor trees and prime factorization.',
    youtube_url: 'https://www.youtube.com/watch?v=3h4UK62Qrbo',
    duration: 600,
    display_order: 2,
    is_active: true,
  },
  {
    id: 'cvid_c5_m3',
    subject_id: 'csubj_c5_math',
    title: '3. Angles, Triangles & Protractor Use',
    description: 'Measure acute, right, and obtuse angles and calculate triangle angle sums.',
    youtube_url: 'https://www.youtube.com/watch?v=9RTM418qfdI',
    duration: 480,
    display_order: 3,
    is_active: true,
  },

  // Class 5 Science
  {
    id: 'cvid_c5_s1',
    subject_id: 'csubj_c5_sci',
    title: '1. Simple Machines & Mechanical Advantage',
    description: 'Explore levers, pulleys, inclined planes, and wheels in everyday life.',
    youtube_url: 'https://www.youtube.com/watch?v=l1Fhsl5Z46E',
    duration: 540,
    display_order: 1,
    is_active: true,
  },
  {
    id: 'cvid_c5_s2',
    subject_id: 'csubj_c5_sci',
    title: '2. Our Solar System & Planetary Motion',
    description: 'Tour the planets, their orbits, moons, and the sun’s gravitational pull.',
    youtube_url: 'https://www.youtube.com/watch?v=libKVRa01L8',
    duration: 720,
    display_order: 2,
    is_active: true,
  },
  {
    id: 'cvid_c5_s3',
    subject_id: 'csubj_c5_sci',
    title: '3. The Skeletal and Muscular System',
    description: 'Understand how bones, joints, and muscles collaborate for movement.',
    youtube_url: 'https://www.youtube.com/watch?v=JpVUqXWZlps',
    duration: 600,
    display_order: 3,
    is_active: true,
  },

  // Class 5 English
  {
    id: 'cvid_c5_e1',
    subject_id: 'csubj_c5_eng',
    title: '1. Adjectives & Degrees of Comparison',
    description: 'Master positive, comparative, and superlative adjective forms.',
    youtube_url: 'https://www.youtube.com/watch?v=vVjZ6b1q88o',
    duration: 480,
    display_order: 1,
    is_active: true,
  },
  {
    id: 'cvid_c5_e2',
    subject_id: 'csubj_c5_eng',
    title: '2. Mastering Verb Tenses',
    description: 'Clearly communicate past, present, and future events in correct tense.',
    youtube_url: 'https://www.youtube.com/watch?v=84HYE8v_Kow',
    duration: 660,
    display_order: 2,
    is_active: true,
  },

  // Class 6 Mathematics
  {
    id: 'cvid_c6_m1',
    subject_id: 'csubj_c6_math',
    title: '1. Integers & the Number Line',
    description: 'Understand positive and negative numbers, opposites, and addition on number lines.',
    youtube_url: 'https://www.youtube.com/watch?v=x0E4vxLydNY',
    duration: 600,
    display_order: 1,
    is_active: true,
  },
  {
    id: 'cvid_c6_m2',
    subject_id: 'csubj_c6_math',
    title: '2. Introduction to Algebra',
    description: 'Discover variables, expressions, and solving simple single-step equations.',
    youtube_url: 'https://www.youtube.com/watch?v=NybHckSEQBI',
    duration: 720,
    display_order: 2,
    is_active: true,
  },
  {
    id: 'cvid_c6_m3',
    subject_id: 'csubj_c6_math',
    title: '3. Ratio and Proportion Fundamentals',
    description: 'Learn to compare quantities, simplify ratios, and solve unit rate problems.',
    youtube_url: 'https://www.youtube.com/watch?v=RQ2nYUBVvqI',
    duration: 540,
    display_order: 3,
    is_active: true,
  },

  // Class 6 Science
  {
    id: 'cvid_c6_s1',
    subject_id: 'csubj_c6_sci',
    title: '1. Components of Food & Balanced Diet',
    description: 'Examine carbohydrates, proteins, fats, vitamins, and deficiency diseases.',
    youtube_url: 'https://www.youtube.com/watch?v=94HYE8v_Kow',
    duration: 480,
    display_order: 1,
    is_active: true,
  },
  {
    id: 'cvid_c6_s2',
    subject_id: 'csubj_c6_sci',
    title: '2. Light, Shadows and Reflections',
    description: 'Learn transparent vs opaque materials, rectilinear propagation, and mirror reflections.',
    youtube_url: 'https://www.youtube.com/watch?v=xyMrLQ4ZI-4',
    duration: 540,
    display_order: 2,
    is_active: true,
  },

  // Class 6 English
  {
    id: 'cvid_c6_e1',
    subject_id: 'csubj_c6_eng',
    title: '1. Prepositions of Place, Time & Direction',
    description: 'Master common preposition rules and avoid frequent usage errors.',
    youtube_url: 'https://www.youtube.com/watch?v=xyMrLQ4ZI-4',
    duration: 480,
    display_order: 1,
    is_active: true,
  },
  {
    id: 'cvid_c6_e2',
    subject_id: 'csubj_c6_eng',
    title: '2. Conjunctions & Clause Connections',
    description: 'Connect sentences with coordinating and subordinating conjunctions.',
    youtube_url: 'https://www.youtube.com/watch?v=48vE_x0uX8E',
    duration: 420,
    display_order: 2,
    is_active: true,
  },

  // ==========================================
  // CLASS 7 COURSES
  // ==========================================
  // Class 7 Mathematics
  {
    id: 'cvid_c7_m1',
    subject_id: 'csubj_c7_math',
    title: '1. Integers: Addition & Multiplication Properties',
    description: 'Rules for multiplying negative numbers, closures, and distributive property.',
    youtube_url: 'https://www.youtube.com/watch?v=1oW_W9bZ7vM',
    duration: 540,
    display_order: 1,
    is_active: true,
  },
  {
    id: 'cvid_c7_m2',
    subject_id: 'csubj_c7_math',
    title: '2. Fractions and Decimals: Division & Multiplication',
    description: 'Master reciprocal fraction division and decimal position calculations.',
    youtube_url: 'https://www.youtube.com/watch?v=ITce7f6K9as',
    duration: 600,
    display_order: 2,
    is_active: true,
  },
  // Class 7 Science
  {
    id: 'cvid_c7_s1',
    subject_id: 'csubj_c7_sci',
    title: '1. Nutrition in Plants: Autotrophs & Heterotrophs',
    description: 'Explore photosynthesis, stomatal mechanisms, and insectivorous adaptations.',
    youtube_url: 'https://www.youtube.com/watch?v=D1Ymc311XS8',
    duration: 480,
    display_order: 1,
    is_active: true,
  },
  {
    id: 'cvid_c7_s2',
    subject_id: 'csubj_c7_sci',
    title: '2. Heat and Temperature: Conduction, Convection & Radiation',
    description: 'Understand thermal energy transfer methods and clinical thermometers.',
    youtube_url: 'https://www.youtube.com/watch?v=wclY8LIC-HE',
    duration: 520,
    display_order: 2,
    is_active: true,
  },

  // ==========================================
  // CLASS 8 COURSES
  // ==========================================
  // Class 8 Mathematics
  {
    id: 'cvid_c8_m1',
    subject_id: 'csubj_c8_math',
    title: '1. Rational Numbers: Operations & Number Line',
    description: 'Learn commutative, associative, and distributive properties of rational numbers.',
    youtube_url: 'https://www.youtube.com/watch?v=ITce7f6K9as',
    duration: 660,
    display_order: 1,
    is_active: true,
  },
  {
    id: 'cvid_c8_m2',
    subject_id: 'csubj_c8_math',
    title: '2. Linear Equations in One Variable',
    description: 'Techniques for solving equations with variables on both sides.',
    youtube_url: 'https://www.youtube.com/watch?v=mvOkMYCygps',
    duration: 720,
    display_order: 2,
    is_active: true,
  },
  {
    id: 'cvid_c8_m3',
    subject_id: 'csubj_c8_math',
    title: '3. Understanding Quadrilaterals & Polygons',
    description: 'Properties of parallelograms, rhombuses, rectangles, and angle sum theorem.',
    youtube_url: 'https://www.youtube.com/watch?v=24Uv8Cl5hvI',
    duration: 580,
    display_order: 3,
    is_active: true,
  },
  // Class 8 Science
  {
    id: 'cvid_c8_s1',
    subject_id: 'csubj_c8_sci',
    title: '1. Crop Production and Agricultural Practices',
    description: 'Study soil preparation, sowing, irrigation, fertilizers, and harvesting.',
    youtube_url: 'https://www.youtube.com/watch?v=ncORPosDrjI',
    duration: 600,
    display_order: 1,
    is_active: true,
  },
  {
    id: 'cvid_c8_s2',
    subject_id: 'csubj_c8_sci',
    title: '2. Microorganisms: Friend and Foe',
    description: 'Explore useful bacteria and harmful pathogens, vaccines, and preservation.',
    youtube_url: 'https://www.youtube.com/watch?v=VwrsL-lCzYo',
    duration: 540,
    display_order: 2,
    is_active: true,
  },
  {
    id: 'cvid_c8_s3',
    subject_id: 'csubj_c8_sci',
    title: '3. Force and Pressure: Fundamentals',
    description: 'Contact and non-contact forces, pressure equation, and atmospheric pressure.',
    youtube_url: 'https://www.youtube.com/watch?v=PqegJUGFtVM',
    duration: 620,
    display_order: 3,
    is_active: true,
  },

  // ==========================================
  // CLASS 9 COURSES
  // ==========================================
  // Class 9 Mathematics
  {
    id: 'cvid_c9_m1',
    subject_id: 'csubj_c9_math',
    title: '1. Number Systems: Irrational Numbers & Real Numbers',
    description: 'Discover decimal expansions of real numbers and operations on radicals.',
    youtube_url: 'https://www.youtube.com/watch?v=1oW_W9bZ7vM',
    duration: 720,
    display_order: 1,
    is_active: true,
  },
  {
    id: 'cvid_c9_m2',
    subject_id: 'csubj_c9_math',
    title: '2. Polynomials: Remainder & Factor Theorems',
    description: 'Zeroes of polynomials, algebraic identities, and factoring quadratics.',
    youtube_url: 'https://www.youtube.com/watch?v=Vm7H0VTlIco',
    duration: 780,
    display_order: 2,
    is_active: true,
  },
  {
    id: 'cvid_c9_m3',
    subject_id: 'csubj_c9_math',
    title: '3. Coordinate Geometry: The Cartesian Plane',
    description: 'Plotting points, quadrants, abscissa, ordinate, and coordinate geometry basics.',
    youtube_url: 'https://www.youtube.com/watch?v=1op92oi5Vq4',
    duration: 480,
    display_order: 3,
    is_active: true,
  },
  // Class 9 Science
  {
    id: 'cvid_c9_s1',
    subject_id: 'csubj_c9_sci',
    title: '1. Matter in Our Surroundings & Phase Changes',
    description: 'Kinetic theory of particles, latent heat of fusion/vaporization, and evaporation.',
    youtube_url: 'https://www.youtube.com/watch?v=wclY8LIC-HE',
    duration: 640,
    display_order: 1,
    is_active: true,
  },
  {
    id: 'cvid_c9_s2',
    subject_id: 'csubj_c9_sci',
    title: '2. The Fundamental Unit of Life: Cell Biology',
    description: 'Plasma membrane, nucleus, cytoplasm, mitochondria, and cell organelles.',
    youtube_url: 'https://www.youtube.com/watch?v=8IlzKri08kk',
    duration: 680,
    display_order: 2,
    is_active: true,
  },
  {
    id: 'cvid_c9_s3',
    subject_id: 'csubj_c9_sci',
    title: '3. Motion: Speed, Velocity & Equations of Motion',
    description: 'Uniform vs non-uniform motion, acceleration, and kinematic motion graphs.',
    youtube_url: 'https://www.youtube.com/watch?v=48vE_x0uX8E',
    duration: 750,
    display_order: 3,
    is_active: true,
  },
  {
    id: 'cvid_c9_s4',
    subject_id: 'csubj_c9_sci',
    title: '4. Force and Newton’s Laws of Motion',
    description: 'Inertia, momentum (p = mv), F = ma, action-reaction pairs, and momentum conservation.',
    youtube_url: 'https://www.youtube.com/watch?v=kKKM8Y-u7ds',
    duration: 700,
    display_order: 4,
    is_active: true,
  },

  // ==========================================
  // CLASS 10 COURSES (System 2 Primary Target)
  // ==========================================
  // Class 10 Mathematics
  {
    id: 'cvid_c10_m1',
    subject_id: 'csubj_c10_math',
    title: '1. Real Numbers: Fundamental Theorem of Arithmetic',
    description: 'Master prime factorisation, proving irrationality of √2 and √3, and HCF/LCM relations.',
    youtube_url: 'https://www.youtube.com/watch?v=1oW_W9bZ7vM',
    duration: 840,
    display_order: 1,
    is_active: true,
  },
  {
    id: 'cvid_c10_m2',
    subject_id: 'csubj_c10_math',
    title: '2. Polynomials: Zeroes & Coefficient Relationships',
    description: 'Geometric meaning of zeroes of a polynomial and sum/product of zeroes formulas.',
    youtube_url: 'https://www.youtube.com/watch?v=Vm7H0VTlIco',
    duration: 780,
    display_order: 2,
    is_active: true,
  },
  {
    id: 'cvid_c10_m3',
    subject_id: 'csubj_c10_math',
    title: '3. Pair of Linear Equations in Two Variables',
    description: 'Substitution, elimination, and graphical solutions for intersecting/parallel lines.',
    youtube_url: 'https://www.youtube.com/watch?v=1op92oi5Vq4',
    duration: 820,
    display_order: 3,
    is_active: true,
  },
  {
    id: 'cvid_c10_m4',
    subject_id: 'csubj_c10_math',
    title: '4. Quadratic Equations & The Quadratic Formula',
    description: 'Roots of quadratic equations by factorisation and discriminant (b² - 4ac) analysis.',
    youtube_url: 'https://www.youtube.com/watch?v=ZBalWWHY4Go',
    duration: 900,
    display_order: 4,
    is_active: true,
  },
  {
    id: 'cvid_c10_m5',
    subject_id: 'csubj_c10_math',
    title: '5. Introduction to Trigonometry: Ratios & Identities',
    description: 'Master sin, cos, tan, cot, sec, cosec on right triangles and sin²θ + cos²θ = 1.',
    youtube_url: 'https://www.youtube.com/watch?v=PUB0TaZ7bhA',
    duration: 960,
    display_order: 5,
    is_active: true,
  },

  // Class 10 Science
  {
    id: 'cvid_c10_s1',
    subject_id: 'csubj_c10_sci',
    title: '1. Chemical Reactions and Equations: Balancing & Types',
    description: 'Combination, decomposition, displacement, double displacement, redox, and balancing equations.',
    youtube_url: 'https://www.youtube.com/watch?v=2Juem0lcifE',
    duration: 840,
    display_order: 1,
    is_active: true,
  },
  {
    id: 'cvid_c10_s2',
    subject_id: 'csubj_c10_sci',
    title: '2. Acids, Bases and Salts: The pH Scale & Chemistry',
    description: 'Reactions with metals, neutralization, indicator color changes, and chlor-alkali process.',
    youtube_url: 'https://www.youtube.com/watch?v=mnbS56HQbaU',
    duration: 780,
    display_order: 2,
    is_active: true,
  },
  {
    id: 'cvid_c10_s3',
    subject_id: 'csubj_c10_sci',
    title: '3. Life Processes: Nutrition, Respiration & Circulation',
    description: 'Human digestive tract enzymes, aerobic vs anaerobic respiration, and double circulation in heart.',
    youtube_url: 'https://www.youtube.com/watch?v=48vE_x0uX8E',
    duration: 900,
    display_order: 3,
    is_active: true,
  },
  {
    id: 'cvid_c10_s4',
    subject_id: 'csubj_c10_sci',
    title: '4. Light: Reflection, Spherical Mirrors & Ray Diagrams',
    description: 'Concave & convex mirror formulas, magnification, Snell’s law of refraction, and lens power.',
    youtube_url: 'https://www.youtube.com/watch?v=gDA_nDXM-ck',
    duration: 920,
    display_order: 4,
    is_active: true,
  },
  {
    id: 'cvid_c10_s5',
    subject_id: 'csubj_c10_sci',
    title: '5. Electricity: Ohm’s Law, Resistance & Circuits',
    description: 'Electric potential, V = IR, factors affecting resistance, series vs parallel connections, and Joule heating.',
    youtube_url: 'https://www.youtube.com/watch?v=8jB74K101_k',
    duration: 950,
    display_order: 5,
    is_active: true,
  },

  // Class 10 English
  {
    id: 'cvid_c10_e1',
    subject_id: 'csubj_c10_eng',
    title: '1. First Flight: A Letter to God Analysis',
    description: 'Key themes of unquestioning faith, irony, character sketch of Lencho, and board exam questions.',
    youtube_url: 'https://www.youtube.com/watch?v=xyMrLQ4ZI-4',
    duration: 620,
    display_order: 1,
    is_active: true,
  },
  {
    id: 'cvid_c10_e2',
    subject_id: 'csubj_c10_eng',
    title: '2. Nelson Mandela: Long Walk to Freedom Overview',
    description: 'Struggle against apartheid, twin obligations of man, courage defined, and literary devices.',
    youtube_url: 'https://www.youtube.com/watch?v=48vE_x0uX8E',
    duration: 680,
    display_order: 2,
    is_active: true,
  },
  {
    id: 'cvid_c10_e3',
    subject_id: 'csubj_c10_eng',
    title: '3. English Grammar: Reported Speech & Active/Passive Voice',
    description: 'Transformation rules, direct to indirect speech tenses, modal shifts, and common pitfalls.',
    youtube_url: 'https://www.youtube.com/watch?v=ITce7f6K9as',
    duration: 600,
    display_order: 3,
    is_active: true,
  },

  // Class 10 Computer Applications
  {
    id: 'cvid_c10_cs1',
    subject_id: 'csubj_c10_cs',
    title: '1. Basics of HTML5 & Web Publishing',
    description: 'Document structure, tags, headings, paragraphs, ordered/unordered lists, and image embedding.',
    youtube_url: 'https://www.youtube.com/watch?v=MDLn5-zSQQI',
    duration: 840,
    display_order: 1,
    is_active: true,
  },
  {
    id: 'cvid_c10_cs2',
    subject_id: 'csubj_c10_cs',
    title: '2. Cyber Ethics, Digital Footprints & Safety',
    description: 'Intellectual property rights, open-source software, phishing, malware prevention, and netiquette.',
    youtube_url: 'https://www.youtube.com/watch?v=inWWhr5tnEA',
    duration: 650,
    display_order: 2,
    is_active: true,
  },
];
