/**
 * Default Curated Course Data for School Students (System 2)
 * Used as seed source and reliable fallback when Supabase table migration is pending.
 */

export const DEFAULT_COURSE_SUBJECTS = [
  // Class 4
  { id: 'csubj_c4_math', class: 'Class 4', subject_name: 'Mathematics', display_order: 1, icon: 'Calculator', is_active: true },
  { id: 'csubj_c4_sci', class: 'Class 4', subject_name: 'Science', display_order: 2, icon: 'FlaskConical', is_active: true },
  { id: 'csubj_c4_eng', class: 'Class 4', subject_name: 'English', display_order: 3, icon: 'BookOpen', is_active: true },

  // Class 5
  { id: 'csubj_c5_math', class: 'Class 5', subject_name: 'Mathematics', display_order: 1, icon: 'Calculator', is_active: true },
  { id: 'csubj_c5_sci', class: 'Class 5', subject_name: 'Science', display_order: 2, icon: 'FlaskConical', is_active: true },
  { id: 'csubj_c5_eng', class: 'Class 5', subject_name: 'English', display_order: 3, icon: 'BookOpen', is_active: true },

  // Class 6
  { id: 'csubj_c6_math', class: 'Class 6', subject_name: 'Mathematics', display_order: 1, icon: 'Calculator', is_active: true },
  { id: 'csubj_c6_sci', class: 'Class 6', subject_name: 'Science', display_order: 2, icon: 'FlaskConical', is_active: true },
  { id: 'csubj_c6_eng', class: 'Class 6', subject_name: 'English', display_order: 3, icon: 'BookOpen', is_active: true },
];

export const DEFAULT_COURSE_VIDEOS = [
  // Class 4 Mathematics
  {
    id: 'cvid_c4_m1',
    subject_id: 'csubj_c4_math',
    title: '1. Introduction to Fractions',
    description: 'Learn what fractions mean, numerators, and denominators using visual shapes.',
    youtube_url: 'https://www.youtube.com/watch?v=ITce7f6K9as',
    duration: 480,
    display_order: 1,
    is_active: true,
  },
  {
    id: 'cvid_c4_m2',
    subject_id: 'csubj_c4_math',
    title: '2. Multiplication & Division Concepts',
    description: 'Master multi-digit multiplication and step-by-step division techniques.',
    youtube_url: 'https://www.youtube.com/watch?v=mvOkMYCygps',
    duration: 600,
    display_order: 2,
    is_active: true,
  },
  {
    id: 'cvid_c4_m3',
    subject_id: 'csubj_c4_math',
    title: '3. 2D Shapes, Symmetry & Geometry',
    description: 'Explore symmetrical patterns, polygons, and geometric spatial properties.',
    youtube_url: 'https://www.youtube.com/watch?v=24Uv8Cl5hvI',
    duration: 420,
    display_order: 3,
    is_active: true,
  },

  // Class 4 Science
  {
    id: 'cvid_c4_s1',
    subject_id: 'csubj_c4_sci',
    title: '1. How Plants Make Food: Photosynthesis',
    description: 'Discover chlorophyll, sunlight absorption, and oxygen production in leaves.',
    youtube_url: 'https://www.youtube.com/watch?v=D1Ymc311XS8',
    duration: 540,
    display_order: 1,
    is_active: true,
  },
  {
    id: 'cvid_c4_s2',
    subject_id: 'csubj_c4_sci',
    title: '2. The Human Digestive System',
    description: 'Follow food on its journey from mouth to stomach and nutrient absorption.',
    youtube_url: 'https://www.youtube.com/watch?v=VwrsL-lCzYo',
    duration: 660,
    display_order: 2,
    is_active: true,
  },
  {
    id: 'cvid_c4_s3',
    subject_id: 'csubj_c4_sci',
    title: '3. States of Matter: Solids, Liquids & Gases',
    description: 'Understand molecular arrangements and phase changes with fun examples.',
    youtube_url: 'https://www.youtube.com/watch?v=wclY8LIC-HE',
    duration: 480,
    display_order: 3,
    is_active: true,
  },
  {
    id: 'cvid_c4_s4',
    subject_id: 'csubj_c4_sci',
    title: '4. The Water Cycle in Nature',
    description: 'Learn how evaporation, condensation, and precipitation circulate Earth’s water.',
    youtube_url: 'https://www.youtube.com/watch?v=ncORPosDrjI',
    duration: 360,
    display_order: 4,
    is_active: true,
  },
  {
    id: 'cvid_c4_s5',
    subject_id: 'csubj_c4_sci',
    title: '5. Adaptations in Animals & Habitats',
    description: 'See how desert, polar, and aquatic animals survive in extreme environments.',
    youtube_url: 'https://www.youtube.com/watch?v=Z3W6n64F1xM',
    duration: 510,
    display_order: 5,
    is_active: true,
  },

  // Class 4 English
  {
    id: 'cvid_c4_e1',
    subject_id: 'csubj_c4_eng',
    title: '1. Nouns: Common, Proper & Collective',
    description: 'Learn to identify different types of nouns with sentence examples.',
    youtube_url: 'https://www.youtube.com/watch?v=84HYE8v_Kow',
    duration: 420,
    display_order: 1,
    is_active: true,
  },
  {
    id: 'cvid_c4_e2',
    subject_id: 'csubj_c4_eng',
    title: '2. Action Verbs & Helping Verbs',
    description: 'Learn how verbs express actions and support sentence clarity.',
    youtube_url: 'https://www.youtube.com/watch?v=Uq_Vw32m_7k',
    duration: 480,
    display_order: 2,
    is_active: true,
  },
  {
    id: 'cvid_c4_e3',
    subject_id: 'csubj_c4_eng',
    title: '3. Subject and Predicate in Sentences',
    description: 'Break down complete sentences into subjects and predicates accurately.',
    youtube_url: 'https://www.youtube.com/watch?v=fdUXxdmhIsw',
    duration: 360,
    display_order: 3,
    is_active: true,
  },
  {
    id: 'cvid_c4_e4',
    subject_id: 'csubj_c4_eng',
    title: '4. Reading Comprehension Skills',
    description: 'Strategies for reading passages, identifying main ideas, and answering questions.',
    youtube_url: 'https://www.youtube.com/watch?v=2y2Bf1t6Iks',
    duration: 540,
    display_order: 4,
    is_active: true,
  },

  // Class 5 Mathematics
  {
    id: 'cvid_c5_m1',
    subject_id: 'csubj_c5_math',
    title: '1. Introduction to Decimals & Place Value',
    description: 'Grasp tenths, hundredths, and converting fractions to decimals.',
    youtube_url: 'https://www.youtube.com/watch?v=t9vbmxPzBGE',
    duration: 540,
    display_order: 1,
    is_active: true,
  },
  {
    id: 'cvid_c5_m2',
    subject_id: 'csubj_c5_math',
    title: '2. Factors, Multiples & Prime Numbers',
    description: 'Find HCF and LCM easily using factor trees and prime factorization.',
    youtube_url: 'https://www.youtube.com/watch?v=3h4UK62Qrbo',
    duration: 600,
    display_order: 2,
    is_active: true,
  },
  {
    id: 'cvid_c5_m3',
    subject_id: 'csubj_c5_math',
    title: '3. Angles, Triangles & Protractor Use',
    description: 'Measure acute, right, and obtuse angles and calculate triangle angle sums.',
    youtube_url: 'https://www.youtube.com/watch?v=9RTM418qfdI',
    duration: 480,
    display_order: 3,
    is_active: true,
  },

  // Class 5 Science
  {
    id: 'cvid_c5_s1',
    subject_id: 'csubj_c5_sci',
    title: '1. Simple Machines & Mechanical Advantage',
    description: 'Explore levers, pulleys, inclined planes, and wheels in everyday life.',
    youtube_url: 'https://www.youtube.com/watch?v=l1Fhsl5Z46E',
    duration: 540,
    display_order: 1,
    is_active: true,
  },
  {
    id: 'cvid_c5_s2',
    subject_id: 'csubj_c5_sci',
    title: '2. Our Solar System & Planetary Motion',
    description: 'Tour the planets, their orbits, moons, and the sun’s gravitational pull.',
    youtube_url: 'https://www.youtube.com/watch?v=libKVRa01L8',
    duration: 720,
    display_order: 2,
    is_active: true,
  },
  {
    id: 'cvid_c5_s3',
    subject_id: 'csubj_c5_sci',
    title: '3. The Skeletal and Muscular System',
    description: 'Understand how bones, joints, and muscles collaborate for movement.',
    youtube_url: 'https://www.youtube.com/watch?v=JpVUqXWZlps',
    duration: 600,
    display_order: 3,
    is_active: true,
  },

  // Class 5 English
  {
    id: 'cvid_c5_e1',
    subject_id: 'csubj_c5_eng',
    title: '1. Adjectives & Degrees of Comparison',
    description: 'Master positive, comparative, and superlative adjective forms.',
    youtube_url: 'https://www.youtube.com/watch?v=vVjZ6b1q88o',
    duration: 480,
    display_order: 1,
    is_active: true,
  },
  {
    id: 'cvid_c5_e2',
    subject_id: 'csubj_c5_eng',
    title: '2. Mastering Verb Tenses',
    description: 'Clearly communicate past, present, and future events in correct tense.',
    youtube_url: 'https://www.youtube.com/watch?v=84HYE8v_Kow',
    duration: 660,
    display_order: 2,
    is_active: true,
  },

  // Class 6 Mathematics
  {
    id: 'cvid_c6_m1',
    subject_id: 'csubj_c6_math',
    title: '1. Integers & the Number Line',
    description: 'Understand positive and negative numbers, opposites, and addition on number lines.',
    youtube_url: 'https://www.youtube.com/watch?v=x0E4vxLydNY',
    duration: 600,
    display_order: 1,
    is_active: true,
  },
  {
    id: 'cvid_c6_m2',
    subject_id: 'csubj_c6_math',
    title: '2. Introduction to Algebra',
    description: 'Discover variables, expressions, and solving simple single-step equations.',
    youtube_url: 'https://www.youtube.com/watch?v=NybHckSEQBI',
    duration: 720,
    display_order: 2,
    is_active: true,
  },
  {
    id: 'cvid_c6_m3',
    subject_id: 'csubj_c6_math',
    title: '3. Ratio and Proportion Fundamentals',
    description: 'Learn to compare quantities, simplify ratios, and solve unit rate problems.',
    youtube_url: 'https://www.youtube.com/watch?v=RQ2nYUBVvqI',
    duration: 540,
    display_order: 3,
    is_active: true,
  },

  // Class 6 Science
  {
    id: 'cvid_c6_s1',
    subject_id: 'csubj_c6_sci',
    title: '1. Components of Food & Balanced Diet',
    description: 'Examine carbohydrates, proteins, fats, vitamins, and deficiency diseases.',
    youtube_url: 'https://www.youtube.com/watch?v=94HYE8v_Kow',
    duration: 480,
    display_order: 1,
    is_active: true,
  },
  {
    id: 'cvid_c6_s2',
    subject_id: 'csubj_c6_sci',
    title: '2. Light, Shadows and Reflections',
    description: 'Learn transparent vs opaque materials, rectilinear propagation, and mirror reflections.',
    youtube_url: 'https://www.youtube.com/watch?v=xyMrLQ4ZI-4',
    duration: 540,
    display_order: 2,
    is_active: true,
  },

  // Class 6 English
  {
    id: 'cvid_c6_e1',
    subject_id: 'csubj_c6_eng',
    title: '1. Prepositions of Place, Time & Direction',
    description: 'Master common preposition rules and avoid frequent usage errors.',
    youtube_url: 'https://www.youtube.com/watch?v=xyMrLQ4ZI-4',
    duration: 480,
    display_order: 1,
    is_active: true,
  },
  {
    id: 'cvid_c6_e2',
    subject_id: 'csubj_c6_eng',
    title: '2. Conjunctions & Clause Connections',
    description: 'Connect sentences with coordinating and subordinating conjunctions.',
    youtube_url: 'https://www.youtube.com/watch?v=48vE_x0uX8E',
    duration: 420,
    display_order: 2,
    is_active: true,
  },
];
